---
- name: "Debug"
  debug: var=item
  loop: "{{ foreman_os_default_templates | default([]) }}"
  loop_control:
    label: "{{ item.operatingsystem }} => {{ item.provisioning_template }}"
  when: foreman_debug

- name: "Create OS template association (fail in check mode)"
  theforeman.foreman.os_default_template:
    operatingsystem: "{{ item.operatingsystem | mandatory }}"
    template_kind: "{{ item.template_kind | mandatory }}"
    provisioning_template: "{{ item.provisioning_template | default(omit)}}"
    state: "{{ item.state | default('present') }}"
    username: "{{ foreman_username }}"
    password: "{{ foreman_password }}"
    server_url: "{{ foreman_server_url }}"
    validate_certs: "{{ foreman_validate_certs | default('true') }}"    
  loop: "{{ foreman_os_default_templates | default([]) }}"
  loop_control:
    label: "{{ item.operatingsystem }} => {{ item.provisioning_template }}"
  ignore_errors: "{{ ansible_check_mode }}"
