---
- name: Set Global Parameters
  theforeman.foreman.global_parameter:
    #    <<: *foreman_auth
    state: "{{ item.state | default('present') }}"
    parameter_type: "{{ item.parameter_type | default(omit) }}"
    name: "{{ item.name }}"
    value: "{{ item.value | mandatory }}"
    username: "{{ foreman_username }}"
    password: "{{ foreman_password }}"
    server_url: "{{ foreman_server_url }}"
    validate_certs: "{{ foreman_validate_certs | default('true') }}"
  loop: "{{ [foreman_global_parameter, foreman_override_global_parameter | default([{}])] |
            community.general.lists_mergeby('name',
                                            recursive=true,
                                            list_merge='prepend_rp') }}"
  loop_control:
    label: "{{ item.name }} => {{ item.value }}"
